# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2.4.0
        with:
           node_version: 14.x
      
      - uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: yarn
          upload-chunk-size: 200
          
      - name: GitHub App token
        uses: tibdex/github-app-token@v1.0.2
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      
      - name: Install and Build
      - run: |
         npm i -g yarn
         yarn
         yarn build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          personal_token: ${{ steps.generate_token.outputs.token }}
          publish_dir: ./build
          external_repository: epic-yeet/epic-yeet.github.io
