name: Build + Deploy
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
           node-version: 14.x
           
      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: ./node_modules
          key: yarn
          
      - name: Generate App Token
        uses: tibdex/github-app-token@v1.0.2
        id: generate_token
        continue-on-error: true
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      
      - name: Install and Build
      - run: |
         npm i -g yarn
         yarn
         yarn build
      
      - name: Deploy (in main repo)
        if: github.repository_owner == 'epic-yeet' & github.github_ref != 'refs/heads/develop'
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          personal_token: ${{ steps.generate_token.outputs.token }}
          publish_dir: ./build
          external_repository: 'epic-yeet/epic-yeet.github.io'
          keep_files: true
